[build]
command = "npm run generate"
publish = "dist"

# [[plugins]]
# package = "netlify-plugin-subfont"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
